version: "3"
services:
  typesense:
    image: docker.io/typesense/typesense:0.25.2
    container_name: typesense
    tty: true
    restart: on-failure
    environment:
      - TYPESENSE_DATA_DIR=/data
      - TYPESENSE_API_KEY=xyz
    volumes:
      - ./typesense-data:/data
    ports:
      # for internal status of the typesense server
      - 8107:8107
      # for actual typesense server
      - 8108:8108
