services:
  typesense:
    image: docker.io/typesense/typesense:27.1
    container_name: typesense
    restart: on-failure
    ports:
      - 8107:8107 # internal status
      - 8108:8108 # typesense server
    volumes:
      - ./typesense-data:/data
      - ./typesense-analytics-data:/analytics-data
    command: |
      --data-dir=/data
      --api-key=xyz
      --enable-search-analytics=true
      --analytics-dir=/analytics-data 
      --analytics-flush-interval=60
      --analytics-minute-rate-limit=100
      --enable-cors
  typesense_dashboard:
    image: ghcr.io/bfritscher/typesense-dashboard:1.9.3
    container_name: typesense_dashboard
    restart: on-failure
    ports:
      - 8109:80
    volumes:
      - ./config/config.json:/srv/config.json
    depends_on:
      - typesense
