name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs
  # Workflows that would otherwise be triggered using `on: push` or
  # `on: pull_request` won't be triggered if you add any of the
  # following strings to the commit message in a push, or the HEAD
  # commit of a pull request:
  # - [skip ci]
  # - [ci skip]
  # - [no ci]
  # - [skip actions]
  # - [actions skip]

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        typesense-version: [0.25.2 26.0]

    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '25'
          elixir-version: '1.14.x'

      - uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mixtest-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mixtest-

      - name: Start Typesense
        uses: jirevwe/typesense-github-action@v1.0.1
        with:
          typesense-version: ${{ matrix.typesense-version }}
          typesense-api-key: xyz

      - name: Install Dependencies
        run: |
          mix local.rebar --if-missing
          mix local.hex --if-missing
          mix deps.get

      - name: Find unused dependencies
        run: mix deps.unlock --check-unused

      - name: Check retired dependencies
        run: mix hex.audit

      - name: Security audit of dependencies
        run: mix deps.audit

      - name: Compile project
        run: mix compile --all-warnings

      - name: run static analysis
        run: mix credo --all --strict

      - name: format files
        run: mix format

      - name: Run tests
        run: mix test

      - name: Post test coverage to Coveralls
        run: mix coveralls.github
