name: LLM
on:
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  llm:
    runs-on: ubuntu-latest
    environment: review

    env:
      MIX_ENV: test
      GOOGLE_GEMINI_API: ${{ secrets.GOOGLE_GEMINI_API }}

    strategy:
      matrix:
        include:
        - typesense: '30.1'
          otp: '25'
          elixir: '1.14'
        - typesense: '30.1'
          otp: '28'
          elixir: '1.18'
        - typesense: '30.0'
          otp: '25'
          elixir: '1.14'
        - typesense: '30.0'
          otp: '28'
          elixir: '1.18'
        - typesense: '29.0'
          otp: '25'
          elixir: '1.14'
        - typesense: '29.0'
          otp: '28'
          elixir: '1.18'

    steps:
      - name: Start Typesense
        run: |
          docker run -id \
          -p 8108:8108 \
          --name typesense \
          -v /tmp/typesense-data:/data \
          -v /tmp/typesense-analytics-data:/analytics-data \
          typesense/typesense:${{ matrix.typesense}} \
          --api-key xyz \
          --data-dir /data \
          --enable-search-analytics=true \
          --analytics-dir=/analytics-data  \
          --analytics-flush-interval=60 \
          --analytics-minute-rate-limit=100 \
          --enable-cors

      - name: Wait for Typesense to be healthy
        shell: bash
        run: |
          start_time=$(date +%s)
          timeout=30
          counter=0
          until curl -s http://localhost:8108/health | grep -q '"ok":true'; do
            if [ $counter -eq $timeout ]; then
              echo "Timed out waiting for Typesense to be healthy"
              exit 1
            fi
            echo "Waiting for Typesense to be healthy..."
            sleep 1
            counter=$((counter + 1))
          done
          end_time=$(date +%s)
          elapsed=$((end_time - start_time))
          echo "Typesense healthcheck elapsed: ${elapsed}s"

      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Setup Elixir/OTP
        uses: erlef/setup-beam@fc68ffb90438ef2936bbb3251622353b3dcb2f93
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Cache typesense-data
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
        with:
          path: |
            typesense-data
          key: ${{ runner.os }}-typesense-data
          restore-keys: |
            ${{ runner.os }}-typesense-data

      - name: Test natural language search
        run: mix test --only nls:true --trace
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

      - name: Post test coverage to Coveralls
        run: mix coveralls.github
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
